export const DYNAMIC_CONTENT_REQUEST = "DYNAMIC_CONTENT_REQUEST";
export const GET_LOGO = "GET_LOGO";
export const UPDATE_LOGO = "UPDATE_LOGO";
export const UPDATE_LOGO_RESET = "UPDATE_LOGO_RESET";
export const DYNAMIC_CONTENT_ERROR = "DYNAMIC_CONTENT_ERROR";
