export const EXPENSE_REQUEST = "EXPENSE_REQUEST";
export const GET_EXPENSE = "GET_EXPENSE";
export const GET_EXPENSES = "GET_EXPENSES";
export const CREATE_EXPENSE = "CREATE_EXPENSE";
export const UPDATE_EXPENSE = "UPDATE_EXPENSE";
export const UPDATE_EXPENSE_RESET = "UPDATE_EXPENSE_RESET";
export const EXPENSE_ERROR = "EXPENSE_ERROR";
export const DELETE_EXPENSE = "EXPENSE_REQUEST";
